name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install project dependencies for pyright check
        run: |
          pip install uv
          uv sync

      - name: Run pre-commit hooks
        run: uvx pre-commit run --all-files
